name: Build and Deploy

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npx tailwindcss -c tailwind.config.js -i ./tailwind.css -o ./styles.css

      # If you have additional build steps (e.g., a static site generator), add them here.
      # - name: Build Site
      #   run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Adjust if your compiled site is in a subfolder
